// export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
// export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
// export const FETCH_BOOK_BY_ID_SUCCESS = 'FETCH_BOOK_BY_ID_SUCCESS';

// export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const FETCH_BASKETS_SUCCESS = 'FETCH_BASKETS_SUCCESS';
export const FETCH_SUBMISSIONS_SUCCESS = 'FETCH_SUBMISSIONS_SUCCESS';
export const FETCH_PREFERENCES_SUCCESS = 'FETCH_PREFERENCES_SUCCESS';
export const APPLY_FILTER='APPLY_FILTER';
export const UPDATE_COUNT='UPDATE_COUNT';
export const CHANGE_SELECTION='CHANGE_SELECTION';
export const FETCH_SECURITIES_SUCCESS='FETCH_SECURITIES_SUCCESS';
export const FETCH_TIMEFRAMES='FETCH_TIMEFRAMES';
